### ISSUE TITLE
App Upgrades

### ISSUE THREAD

**Issue by jeremy-farrance** [2sic/app-podcast#1]
Do you foresee any or all apps being able to upgrade in the future? Similar to DNN modules. For example, someday when this Podcast app goes from v1 to v2.x, will there be a simple way to upgrade? This has been especially painful for us on the Content app, 

Some thoughts...
 
I think one of the main hurdles at this point could be resolved and avoided. I am guessing that in most cases people install an app and then directly customize the Views and sometimes also the data and queries. This alone makes it hard or impossible to upgrade. 

What if apps evolved slightly and you added a few features to 2sxc/apps? 
1. Add an App setting that flags it as upgrade-able; this would "lock-down" the assets (queries, views, assets, etc) so they don't get modified. Essentially make them read-only. 
 
**Note:** that this idea/pattern seems to be very similar to the recent changes for [Polymorphism](https://docs.2sxc.org/specs/cms/polymorph.html). In addition to the examples of Live, Staging, Next, why NOT have a locked, as-is app version set that only changes via upgrade? 

Now you just need to add one or a few features to make the app easy to customize. 

2. Make it simple for us to clone an Asset and give it a new name (in one step). It is frustrating how many steps it actually takes to copy a view and get all the settings right.

Now you can upgrade and replace all the assets; core views and other things (queries, etc) and also upgrade the data accounting for field name changes and data migrating like DNN modules do.
 
I realize there is a lot more to this, but 1 and 2 above would really start to get things aligned so that it would be become possible in the future. 
 
Maybe I should repost this as an issue/feature request on the 2sxc project?

**Comment by iJungleboy** [comment]
So there are various aspects to this, but I believe it would be best to open a general RFC in the main 2sxc issues. So I'll close this, please open it there. thx!
