### ISSUE TITLE
Formatting Error in Podcast v2.3.1

### ISSUE THREAD

**Issue by skarpik** [2sic/app-podcast#18]
There appears to be a small bug in the formatting in the Podcast app v2.3.1 (DNN 9.11.0, 2sxc v15.0.0, 2Shine v5.0.5).

Here is what it looks like "out-of-the-box":

![Podcast Bug - before fix](https://user-images.githubusercontent.com/3846223/210183370-3ef60804-2c90-4920-aeed-c85d6a8a7c86.jpg)

The RSS symbol is not right-aligned and it is squeezed into an oval shape.

The culprit appears to be line 50 in _Channel.cshtml:

<div class="card-text text-muted mb-0 mt-2 align-self-end">

Changing <div>...</div> to <p>...</p> fixes the alignment. Deleting the "mt-2" fixes the distortion of the RSS symbol.

Here is the new code:
```
<p class="card-text text-muted mb-0 align-self-end">
```
and the result:

![Podcast Bug - after fix](https://user-images.githubusercontent.com/3846223/210183479-d0b06f26-d54c-44cf-805f-efb8f53c174b.jpg)

------------------

There is one other thing that I noticed but I don't know whether it is a formatting glitch or it is this way by design. 

The "+" symbol at the left seems oddly placed (see below) but maybe it has to be there because of the "pencil-plus-3 dots" controls at the right.

![Podcast - Odd Formatting](https://user-images.githubusercontent.com/3846223/210183644-1878ee8d-8b77-49ca-8139-d4bde1f08696.jpg)

**Comment by iJungleboy** [comment]
@skarpik thx
@ropalko pls fix and queue for publishing again ;)

**Comment by skarpik** [comment]
Fixed (months ago). Thanks.
