### ISSUE TITLE
Bug in Podcast version 2.5.0 and version 2.5.1

### ISSUE THREAD

**Issue by skarpik** [2sic/app-podcast#21]
**Bug Description:** 

Episode descriptions for podcasts belonging to a channel are not properly displayed. They simply repeat the channel title and description text (see the screen grab below).

I discovered this bug in 2sxc v16.07.00. Confirmed also in 2sxc v17.01.03.

-----------

@iJungleboy - I believe that the changes below to Channel.PartEpisode.cshtml fix the bug:

**Comment out line 5:**

`    //var channelPartContent = MyItem;`

(we don't need the variable channelPartContent, so this line of code can actually be deleted) 

**Replace line 8:**

`    var episodeToolbar = Kit.Toolbar.Default().DetectDemo(channelPartContent).Layout("-").Delete();`

with

`    var episodeToolbar = Kit.Toolbar.Default().DetectDemo(episode).Layout("-").Delete();`

**Replace line 20 with:**

`    <h5 class="m-0">@channelPartContent.String("Title")</h5>`

with

`    <h5 class="m-0">@episode.String("Title")</h5>`

**Replace line 21:**

`    @channelPartContent.Html("Description").Class("text-muted")`

with

`    @episode.Html("Description").Class("text-muted")`

**Summary:**

Replace "channelPartContent" with "episode"  in everywhere in Channel.PartEpisode.cshtml.

<img width="870" alt="Screenshot 2024-01-27 034600" src="https://github.com/2sic/app-podcast/assets/3846223/4b55df45-1920-49e5-a9db-532b92ff78bf">

**Comment by iJungleboy** [comment]
@skarpik thanks for spotting this.

We'll try to fix in 1-2 weeks.

**Comment by Dominikg77** [comment]
@skarpik @jeremy-farrance 

Thank you for the detailed explanation. This bug happened when switching from Razor 14 to Typed.
I have fixed it and created a new release of version [Release v02.05.02](https://github.com/2sic/app-podcast/releases/tag/v02.05.02)

**Comment by skarpik** [comment]
Thanks @iJungleboy  and @Dominikg77
